version: '3'

services:
  nodeapp:
    build: .
    container_name: tester-online-site
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/tester
    networks:
      - tester-network

  mongodb:
    image: mongo:6
    container_name: tester-online-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - tester-network

volumes:
  mongo-data:

networks:
  tester-network: